POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hdHRpbcO2dCIsImlkIjoiNWE4OTY5ZmVhYjJmNTY2ZDYxNmFiMWNjIiwiaWF0IjoxNTE4OTU1MDM1fQ.33Cl35UEZBrvyyQVc8jtdAmPTjUDuaT2LJL24xNNOVo

{
  "title": "Testiblogi2",
  "author": "J Mannisto",
  "url": "http://www.example.com",
  "likes": 2
}

# {
#   "title": "Sparkfun - START SOMETHING",
#   "author": "Feldi",
#   "url": "https://www.sparkfun.com/news/2597",
#   "likes": 0
# }